utterances_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/dataset/"  # /training/
constraint_gt_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/constraints_gt/"
prompt_to_evaluate: "sheng"
llm_to_evaluate: "deepseek-v3" # gpt-4o
random_seed: 0
number_of_apis_to_evaluate: 50

embedding_model: 
  cosine_similarity: "sentence-transformers/all-mpnet-base-v2"
  bertscore: "microsoft/deberta-xlarge-mnli"

evaluation:
  naturalness: true
  cohen_kappa: false
  parameter_diversity: false
  semantic_relevance: false
  constraint_adherance: false

llm_as_judge:
  name:
    - "anthropic/claude-3-7-sonnet-latest"
    # - "anthropic/claude-4-sonnet"
    # - "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
    # - "gpt-5.1"
    # - "anthropic/claude-3-7-sonnet-latest"    
  url: 
    - https://api.deepinfra.com/v1/openai
    # - https://api.deepinfra.com/v1/openai
    # - https://api.openai.com/v1    
  api_key:
    - "eISv4S64AAzKi3mc4LomEigBvTCvC3dd"
    # - "eISv4S64AAzKi3mc4LomEigBvTCvC3dd"
    # - "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"    
  temperature: 0.0