dataset_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/dataset"
output_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/training"
prompt_design: "sheng"
llm_name: "gpt-4o" #"gpt-4o" "deepseek-v3"
