training_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/training"
testing_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/testing"
output_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/models"
prompt_design: "sheng"  # (Prompt design strategy for training) 
llm_name: "gpt-4o" #"gpt-4o" "deepseek-v3" (LLM used for generating training data)

training_params:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  epochs: 5
  train_batch_size: 22 # 28
  learning_rate: 2e-5
  warmup_steps: 500
  max_seq_length: 512
