# dataset
oas_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/tools"
output_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/dataset"
llm_name: "gpt-4o" #"gpt-4" "deepseek-ai/DeepSeek-V3"
llm_url: "https://api.openai.com/v1" #"https://api.deepinfra.com/v1/openai" "https://api.openai.com/v1"
llm_temp: 0.0
utterances: 10