training_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/training"
testing_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/testing"
output_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/models"
prompt_design: "constraint-aware"  # Prompt design strategy for training
llm_name: "deepseek-v3" # LLM used for generating training data

training_params:
  model_name: "NovaSearch/stella_en_400M_v5" 
  epochs: 1 
  train_batch_size: 16 # 28
  learning_rate: 2e-5
  warmup_steps: 500
  max_seq_length: 512
