dataset_path: "/home/vitor/Documents/phd/ConstraintAPIBench/data/training"
output_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/models"
prompt_design: "sheng"  # (Prompt design strategy for training) 
llm_name: "gpt-4o" #"gpt-4o" "deepseek-v3" (LLM used for generating training data)

training_params:
  model_name: "bert-base-uncased"
  epochs: 5
  train_batch_size: 32
  batch_size: 16
  learning_rate: 2e-5
  warmup_steps: 500
  max_seq_length: 512
