utterances_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/dataset/"  # /training/
prompt_to_evaluate: "constraint-aware"
llm_to_evaluate: "gpt-4o"
random_seed: 1
number_of_apis_to_evaluate: 10

embedding_model: 
  cosine_similarity: "sentence-transformers/all-mpnet-base-v2"
  bertscore: "microsoft/deberta-xlarge-mnli"

evaluation:
  naturalness: false
  parameter_diversity: true
  semantic_relevance: true

llm_as_judge:
  name:
    - "gpt-4.1-mini"
    - "anthropic/claude-4-sonnet"
    - "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
  url: 
    - https://api.openai.com/v1
    - https://api.deepinfra.com/v1/openai
    - https://api.deepinfra.com/v1/openai
  api_key:
    - "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"
    - "eISv4S64AAzKi3mc4LomEigBvTCvC3dd"
    - "eISv4S64AAzKi3mc4LomEigBvTCvC3dd"
  temperature: 0.0