utterances_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/dataset/"  # /training/
constraint_gt_folder: "/home/vitor/Documents/phd/ConstraintAPIBench/data/constraints_gt/"
prompt_to_evaluate: "sheng"  # constraint-aware  sheng
llm_to_evaluate: "deepseek-v3" # gpt-4o
random_seed: 0
number_of_apis_to_evaluate: 50 # 50

embedding_model: 
  cosine_similarity: "sentence-transformers/all-mpnet-base-v2"
  bertscore: "microsoft/deberta-xlarge-mnli"

evaluation:
  naturalness: true
  cohen_kappa: true
  parameter_diversity: false
  semantic_relevance: false
  constraint_adherance: false

llm_as_judge:
  name:
    - "gpt-4.1"
    - "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
  url: 
    - https://api.openai.com/v1 
    - https://api.deepinfra.com/v1/openai
  api_key:
    - "openai_api_key_here"
    - "deepinfra_api_key_here"
  temperature: 0.0